"""empty message

Revision ID: 5c158644cc09
Revises: aed8bac5375d
Create Date: 2019-12-10 17:36:35.994702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c158644cc09'
down_revision = 'aed8bac5375d'
branch_labels = None
depends_on = None
connection = op.get_bind()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BookTypes', sa.Column('minimumCharge', sa.Float(), nullable=True))
    op.add_column('BookTypes', sa.Column('minimumRetention', sa.Integer(), nullable=True))
    op.add_column('BookTypes', sa.Column('trialCharge', sa.Float(), nullable=True))
    op.add_column('BookTypes', sa.Column('trialPeriod', sa.Integer(), nullable=True))
    connection.execute("""
                                Update "BookTypes" set "minimumCharge"=2, "minimumRetention"=2, "trialCharge"=1, 
                                "trialPeriod"=2 where "type"='regular';
                                """)
    connection.execute("""
                                   Update "BookTypes" set "minimumCharge"=4.5, "minimumRetention"=3 where "type"='novel';
                                   """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BookTypes', 'trialPeriod')
    op.drop_column('BookTypes', 'trialCharge')
    op.drop_column('BookTypes', 'minimumRetention')
    op.drop_column('BookTypes', 'minimumCharge')
    # ### end Alembic commands ###
