"""empty message

Revision ID: aed8bac5375d
Revises: 
Create Date: 2019-12-10 13:30:45.562666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed8bac5375d'
down_revision = None
branch_labels = None
depends_on = None
connection = op.get_bind()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BookTypes',
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('charge', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('type'),
    sa.UniqueConstraint('type')
    )
    connection.execute("""
                    INSERT INTO "BookTypes"("type", "charge")
                	VALUES ('regular','1.5'), ('fiction','3'), ('novel','1.5');    
                    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BookTypes')
    # ### end Alembic commands ###
